/* ============================================================
   知识公社 · 全网免费学习资源总库 · 数据
   ------------------------------------------------------------
   字段：t 名称 | u 链接 | d 简介 | g 板块(下标) | s 子类
        ty 类型 | f 免费程度 | o 可离线 | w 1=需国际网络/直连不稳
   收录原则：免费、官方、无版权风险优先；中国大陆可直连优先。
   ============================================================ */
window.LIB_DATA = {
  gen: '2026-10-03',
  groups: ['世赛·职业技能', '算法竞赛', '升学考试', '公务员·编制', '红色经典·人文古籍', '开放课程·电子书', '编程·IT·工具'],
  items: [

  /* ============ 0 世赛·职业技能 ============ */
  {t:'世赛官方·云计算赛项',u:'https://worldskills.org/skills/id/545/',d:'世赛官方云计算赛项页：赛项介绍、职业标准与官方文件入口',g:0,s:'官方赛项与标准',ty:'官网',f:'完全免费',o:'可下载'},
  {t:'世赛官方·信息安全赛项',u:'https://worldskills.org/skills/id/546/',d:'世赛官方网络安全赛项页，含竞赛说明与文档入口',g:0,s:'官方赛项与标准',ty:'官网',f:'完全免费',o:'可下载'},
  {t:'世赛官方·网站设计与开发赛项',u:'https://worldskills.org/skills/id/127/',d:'世赛官方网站技术赛项页',g:0,s:'官方赛项与标准',ty:'官网',f:'完全免费',o:'可下载'},
  {t:'世赛官方·网络系统管理赛项',u:'https://worldskills.org/skills/id/212/',d:'世赛官方 IT 网络系统管理赛项页',g:0,s:'官方赛项与标准',ty:'官网',f:'完全免费',o:'可下载'},
  {t:'世赛官方·信息网络布线赛项',u:'https://worldskills.org/skills/id/82/',d:'世赛官方信息网络布线（ICT 网络基础设施）赛项页',g:0,s:'官方赛项与标准',ty:'官网',f:'完全免费',o:'可下载'},
  {t:'WorldSkills 职业标准库 WSOS',u:'https://worldskills.org/what/projects/wsos/',d:'各届世赛职业标准（WSOS）发布页，备考总纲的权威出处',g:0,s:'官方赛项与标准',ty:'规程文档',f:'完全免费',o:'可下载'},
  {t:'WorldSkills 历届成绩库',u:'https://results.worldskills.org',d:'世赛历届各赛项成绩与选手名次官方查询库',g:0,s:'官方赛项与标准',ty:'官网',f:'完全免费',o:'在线'},
  {t:'WorldSkills 官方视频总汇',u:'https://worldskills.org/media/videos',d:'官方视频入口，Vimeo 展示 2022 特别赛 / 喀山 2019 素材',g:0,s:'视频资源',ty:'视频',f:'完全免费',o:'可下载'},
  {t:'WSC2019 韩国HRD 技术描述 PDF',u:'https://meister.hrdkorea.or.kr/uploads/jobManual/02-Information-Network-Cabling/WSC2019_TD02_EN.pdf',d:'布线赛项技术描述官方 PDF，按同路径模式可检索其他赛项 TD',g:0,s:'官方赛项与标准',ty:'规程文档',f:'完全免费',o:'可下载'},
  {t:'WSC2022 特别赛官方站',u:'https://worldskills2022se.com',d:'2022 世界技能大赛特别赛官方信息站：15 个分赛场、24 个赛项',g:0,s:'官方赛项与标准',ty:'官网',f:'完全免费',o:'在线'},
  {t:'上海第48届世赛官网',u:'https://worldskills2026.com',d:'48 届世赛（2026 上海）官方站，含赛项介绍与官方视频页',g:0,s:'官方赛项与标准',ty:'官网',f:'完全免费',o:'部分可下载'},
  {t:'WorldSkills 历史档案馆',u:'https://worldskillsarchive.org',d:'世赛官方历史档案：1940 年代至今文档、照片、影像检索',g:0,s:'官方赛项与标准',ty:'官网',f:'完全免费',o:'在线'},
  {t:'世界技能大赛中国（人社部）',u:'http://worldskillschina.mohrss.gov.cn',d:'世赛中国组委会官网：选拔赛通知、赛项介绍、集训基地与技术文件',g:0,s:'国内赛项与规程',ty:'官网',f:'完全免费',o:'可下载'},
  {t:'世赛资源共享计划',u:'https://worldskills.jishiba.cn',d:'国内世赛社区：里昂 2024 全部赛题下载指南、历届试题交流（注册）',g:0,s:'国内赛项与规程',ty:'题库·社区',f:'免费(注册)',o:'可下载'},
  {t:'技能人才评价证书全国联网查询',u:'http://zscx.osta.org.cn',d:'人社部 OSTA：职业技能等级 / 职业资格证书查询与国家职业标准目录',g:0,s:'国内赛项与规程',ty:'官网',f:'完全免费',o:'在线'},
  {t:'全国职业院校技能大赛（执委会）',u:'http://www.chinaskills-jsw.org',d:'「规程赛题」「资源转化」栏目发布各年度赛项规程与正式赛卷 PDF（GZ073 网管 / GZ075 云计算等）',g:0,s:'国内赛项与规程',ty:'规程文档',f:'完全免费',o:'可下载'},
  {t:'全国职业院校技能大赛（主站）',u:'http://www.nvsc.com.cn',d:'国赛主站，按年度发布制度文件与大赛动态',g:0,s:'国内赛项与规程',ty:'官网',f:'完全免费',o:'在线'},
  {t:'山东省职业院校技能大赛',u:'https://sdskills.sdei.edu.cn',d:'省级选拔赛官网样例：赛项规程与赛题随年度发布，各省均有同类站点',g:0,s:'国内赛项与规程',ty:'规程文档',f:'完全免费',o:'可下载'},
  {t:'一带一路暨金砖国家技能大赛',u:'http://www.brskills.com',d:'金砖 / 一带一路技能大赛官网，赛项通知与技术文件',g:0,s:'国内赛项与规程',ty:'官网',f:'完全免费',o:'可下载'},
  {t:'金砖大赛信息服务平台',u:'https://www.bricsacademy.org.cn/signup/index',d:'金砖大赛官方报名与赛项文件平台（含云计算、信息安全等赛项）',g:0,s:'国内赛项与规程',ty:'官网',f:'免费(注册)',o:'在线'},
  {t:'华为 eNSP Pro 官方下载',u:'https://support.huawei.com/enterprise/zh/training-and-certification-service/ensp-pro-pid-260215817',d:'华为官方数通模拟器（支持 NE/CE/VXLAN/SR），注册华为账号官方直下',g:0,s:'模拟器与软件',ty:'软件下载',f:'免费(注册)',o:'可下载'},
  {t:'eNSP Pro 官方百科（安装说明）',u:'https://info.support.huawei.com/info-finder/encyclopedia/zh/eNSP+Pro.html',d:'官方说明：eNSP Pro 是什么、如何下载安装、与 VirtualBox 配置步骤',g:0,s:'模拟器与软件',ty:'文档',f:'完全免费',o:'可下载'},
  {t:'Cisco Packet Tracer',u:'https://www.netacad.com/courses/packet-tracer',d:'思科官方网络模拟器，NetAcad 免费注册后下载，离线模拟路由/交换/无线',g:0,s:'模拟器与软件',ty:'软件下载',f:'免费(注册)',o:'可下载'},
  {t:'GNS3',u:'https://www.gns3.com/software',d:'开源免费网络仿真平台，可搭配 GNS3 VM 运行重型镜像',g:0,s:'模拟器与软件',ty:'软件下载',f:'完全免费',o:'可下载'},
  {t:'EVE-NG 社区版',u:'https://www.eve-ng.net',d:'多厂商节点统一仿真的经典平台，社区版免费（OVA / 裸机 ISO）',g:0,s:'模拟器与软件',ty:'软件下载',f:'完全免费',o:'可下载'},
  {t:'H3C HCL 华三云实验室',u:'https://www.h3c.com/cn/Service/Document_Software/Software_Download/Other_Product/H3C_Cloud_Lab/Catalog/HCL/',d:'H3C 官方免费模拟器，模拟 MSR 路由 / S5820 交换 / F1060 防火墙',g:0,s:'模拟器与软件',ty:'软件下载',f:'完全免费',o:'可下载'},
  {t:'VMware Workstation Pro 个人版',u:'https://support.broadcom.com',d:'Broadcom 收购后个人使用完全免费（选 for Personal Use，注册下载）',g:0,s:'模拟器与软件',ty:'软件下载',f:'免费(注册)',o:'可下载'},
  {t:'VirtualBox',u:'https://www.virtualbox.org/wiki/Downloads',d:'Oracle 免费开源虚拟机，eNSP / EVE-NG / 靶场的通用底座',g:0,s:'模拟器与软件',ty:'软件下载',f:'完全免费',o:'可下载'},
  {t:'华为人才在线',u:'https://talent.shixizhi.huawei.com',d:'华为官方人才平台：HCIA/HCIP（数通/云/安全）免费课程与模拟题库',g:0,s:'认证自学',ty:'课程·题库',f:'免费(注册)',o:'在线'},
  {t:'NetAcad 网络基础课（中文）',u:'https://www.netacad.com/courses/networking-basics?courseLang=zh-CN',d:'思科官方免费自学课（中文界面），零基础网络入门 + 数字徽章',g:0,s:'认证自学',ty:'课程',f:'免费(注册)',o:'在线'},
  {t:'NetAcad CCNA 系列中文课',u:'https://www.netacad.com/zh/courses/ccna-enterprise-networking-security-automation?courseLang=zh-CN',d:'CCNA 备考官方课（企业网络 / 安全 / 自动化），免费自学',g:0,s:'认证自学',ty:'课程',f:'免费(注册)',o:'在线'},
  {t:'NetAcad Linux Essentials',u:'https://www.netacad.com/courses/linux-essentials',d:'思科官方免费 Linux 入门课，对齐 LPIC-1 / Linux+ 知识体系',g:0,s:'认证自学',ty:'课程',f:'免费(注册)',o:'在线'},
  {t:'Microsoft Learn 中文',u:'https://learn.microsoft.com/zh-cn/training/',d:'微软官方免费学习路径（AZ-900/AZ-104/安全等），含免费沙盒动手实验',g:0,s:'认证自学',ty:'课程·文档',f:'完全免费',o:'可下载'},
  {t:'AWS Skill Builder 免费层',u:'https://skillbuilder.aws',d:'AWS 官方学习平台，600+ 门免费数字课程（筛选 Price=Free），含云从业者备考',g:0,s:'认证自学',ty:'课程',f:'免费(注册)',o:'在线'},
  {t:'阿里云大学（开发者学堂）',u:'https://edu.aliyun.com',d:'阿里云官方课程平台：ACA 认证免费课、免费云资源额度领取',g:0,s:'认证自学',ty:'课程',f:'部分免费',o:'在线'},
  {t:'腾讯云认证中心',u:'https://cloud.tencent.com/developer/certification',d:'腾讯云官方认证页，含免费公开课与备考资料入口',g:0,s:'认证自学',ty:'课程·题库',f:'部分免费',o:'在线'},
  {t:'Linux 基金会免费课程库',u:'https://training.linuxfoundation.org/resources/',d:'官方免费课程筛选页（LFS101《Introduction to Linux》等经典课）',g:0,s:'认证自学',ty:'课程',f:'免费(注册)',o:'在线'},
  {t:'Linux 基金会开源软件学园（中文）',u:'https://training.linuxfoundation.cn',d:'Linux 基金会中文站，精选中文免费课程与认证路径',g:0,s:'认证自学',ty:'课程',f:'部分免费',o:'在线'},
  {t:'LPI 官方备考资料',u:'https://learning.lpi.org',d:'Linux Professional Institute 官方备考库：LPIC-1/2/3 免费学习目标与样题',g:0,s:'认证自学',ty:'题库·文档',f:'完全免费',o:'可下载'},
  {t:'Red Hat Developer 学习',u:'https://developers.redhat.com/learn',d:'红帽免费学习路径 + RHEL 开发者订阅（可本地装 RHEL 练 RHCSA）',g:0,s:'认证自学',ty:'课程·软件',f:'免费(注册)',o:'可下载'},
  {t:'蓝桥云课（原实验楼）',u:'https://www.lanqiao.cn/courses/',d:'浏览器内在线 Linux / Docker / 云计算实验环境，大量免费课程可筛选',g:0,s:'实验平台与靶场',ty:'实验平台',f:'部分免费',o:'在线'},
  {t:'华为云沙箱实验室 KooLabs',u:'https://lab.connect.huaweicloud.com',d:'华为云官方免费实操平台：ECS/OBS/云网络等真实云环境一键开实验',g:0,s:'实验平台与靶场',ty:'实验平台',f:'免费(注册)',o:'在线'},
  {t:'Killercoda',u:'https://killercoda.com',d:'Katacoda 继任者：浏览器内免费交互场景（K8s/Docker/Linux/网络），CKA 备考常用',g:0,s:'实验平台与靶场',ty:'实验平台',f:'完全免费',o:'在线'},
  {t:'Play with Docker',u:'https://labs.play-with-docker.com',d:'Docker 官方免费浏览器沙盒，DinD 实验场',g:0,s:'实验平台与靶场',ty:'实验平台',f:'免费(注册)',o:'在线'},
  {t:'Play with Kubernetes',u:'https://labs.play-with-k8s.com',d:'K8s 官方推荐免费多节点临时集群（单次约 4 小时）',g:0,s:'实验平台与靶场',ty:'实验平台',f:'完全免费',o:'在线'},
  {t:'OverTheWire: Bandit',u:'https://overthewire.org/wargames/bandit/',d:'经典 SSH 闯关 Linux 命令行 wargame，安全 / 运维入门首选',g:0,s:'实验平台与靶场',ty:'靶场',f:'完全免费',o:'在线'},
  {t:'VulnHub',u:'https://www.vulnhub.com',d:'200+ 漏洞虚拟机免费下载（OVA/VDI），VirtualBox / VMware 离线打靶',g:0,s:'实验平台与靶场',ty:'靶场·虚拟机',f:'完全免费',o:'可下载'},
  {t:'Hack The Box 免费层',u:'https://www.hackthebox.com',d:'免费注册可访问约 20 台在线靶机 + HTB Academy Tier 0 免费模块',g:0,s:'实验平台与靶场',ty:'靶场',f:'免费(注册)',o:'在线'},
  {t:'DVWA 靶场',u:'https://github.com/digininja/DVWA',d:'经典 PHP Web 漏洞靶场（SQL 注入/XSS/文件上传，四档难度），本地或 Docker 部署',g:0,s:'实验平台与靶场',ty:'靶场·开源',f:'完全免费',o:'本地部署'},
  {t:'Pikachu 靶场',u:'https://github.com/zhuifengshaonianhanlu/pikachu',d:'国产中文 Web 漏洞练习平台，漏洞类型全，phpstudy 即可搭建',g:0,s:'实验平台与靶场',ty:'靶场·开源',f:'完全免费',o:'本地部署'},
  {t:'Vulhub',u:'https://github.com/vulhub/vulhub',d:'Docker Compose 一键复现真实 CVE 的开源漏洞环境合集（中文文档）',g:0,s:'实验平台与靶场',ty:'靶场·开源',f:'完全免费',o:'本地部署'},
  {t:'WorldSkills 官方 YouTube',u:'https://www.youtube.com/@WorldSkillsTV',d:'官方频道约 1500 条视频：历届开闭幕式与各赛项赛场纪实（分 playlist）',g:0,s:'视频资源',ty:'视频',f:'完全免费',o:'在线',w:1},
  {t:'WorldSkills 官方 Vimeo',u:'https://vimeo.com/worldskills',d:'官方 Vimeo 空间：2022 特别赛、喀山 2019 展示素材提供下载',g:0,s:'视频资源',ty:'视频',f:'完全免费',o:'可下载',w:1},
  {t:'上海2026世赛官方视频页',u:'https://worldskills2026.com/video',d:'48 届世赛官方集锦、开闭幕式与赛项展示，部分视频可直接下载',g:0,s:'视频资源',ty:'视频',f:'完全免费',o:'部分可下载'},
  {t:'B站·世赛视频聚合',u:'https://search.bilibili.com/all?keyword=%E4%B8%96%E7%95%8C%E6%8A%80%E8%83%BD%E5%A4%A7%E8%B5%9B',d:'站内聚合世赛开闭幕式、赛项演示、中国集训队纪录等视频',g:0,s:'视频资源',ty:'视频',f:'完全免费',o:'App缓存'},

  /* ============ 1 算法竞赛 ============ */
  {t:'OI Wiki',u:'https://oi-wiki.org',d:'中文算法竞赛知识库最大的开源 Wiki，竞赛知识点全覆盖，可下载离线版',g:1,s:'知识库 Wiki',ty:'Wiki·开源',f:'完全免费',o:'可下载'},
  {t:'Hello 算法',u:'https://www.hello-algo.com',d:'动画图解数据结构与算法的开源书（12 种语言代码），可免费下载 PDF',g:1,s:'知识库 Wiki',ty:'开源书',f:'完全免费',o:'可下载'},
  {t:'cp-algorithms 中文版',u:'https://cp-algorithms.com',d:'国际知名算法英文站（有中文翻译），数论/图论/字符串专题最强讲义',g:1,s:'知识库 Wiki',ty:'Wiki',f:'完全免费',o:'可下载'},
  {t:'visualgo 算法可视化',u:'https://visualgo.net/zh',d:'新加坡国大出品，数据结构与算法动画可视化，有中文界面',g:1,s:'知识库 Wiki',ty:'可视化',f:'完全免费',o:'在线'},
  {t:'USACO Guide',u:'https://usaco.guide',d:'USACO 官方推荐的免费备赛指南：Bronze→Platinum 路线图、分类题单与视频，开源',g:1,s:'知识库 Wiki',ty:'Wiki',f:'完全免费',o:'可下载'},
  {t:'Codeforces',u:'https://codeforces.com',d:'全球最大竞技编程 OJ，本公社已内置 11425 题离线索引',g:1,s:'OJ 题库',ty:'OJ',f:'完全免费',o:'在线'},
  {t:'AtCoder',u:'https://atcoder.jp',d:'日本知名 OJ，题面简洁质量高，本公社已内置 9600 题离线索引',g:1,s:'OJ 题库',ty:'OJ',f:'完全免费',o:'在线'},
  {t:'洛谷',u:'https://www.luogu.com.cn',d:'国内最大算法竞赛社区 OJ，官方题单 / 训练营 / 互助题解',g:1,s:'OJ 题库',ty:'OJ',f:'完全免费',o:'在线'},
  {t:'牛客网',u:'https://www.nowcoder.com',d:'国内刷题+求职社区：NOIP/蓝桥杯/企业真题与笔试题库',g:1,s:'OJ 题库',ty:'OJ·题库',f:'部分免费',o:'在线'},
  {t:'AcWing',u:'https://www.acwing.com',d:'算法学习社区：题库 + 免费公开课 + 蓝桥杯/NOIP 辅导',g:1,s:'OJ 题库',ty:'OJ·课程',f:'部分免费',o:'在线'},
  {t:'LeetCode 力扣',u:'https://leetcode.cn',d:'国内版力扣，面试算法题库，免费题量充足，题解社区活跃',g:1,s:'OJ 题库',ty:'OJ',f:'部分免费',o:'在线'},
  {t:'Vjudge',u:'https://vjudge.net',d:'聚合各 OJ 题目的虚拟评测站，组队刷题方便',g:1,s:'OJ 题库',ty:'OJ',f:'完全免费',o:'在线'},
  {t:'UOJ',u:'https://uoj.ac',d:'Universal Online Judge，国内高质量 OJ，NOI 系题多',g:1,s:'OJ 题库',ty:'OJ',f:'完全免费',o:'在线'},
  {t:'LibreOJ (LOJ)',u:'https://loj.ac',d:'开源 OJ，收录 NOIP / NOI 系列历年真题与经典专题',g:1,s:'OJ 题库',ty:'OJ',f:'完全免费',o:'在线'},
  {t:'CCF CSP 认证真题',u:'https://www.cspro.org',d:'中国计算机学会 CSP 能力认证官方站，历年真题可练',g:1,s:'真题官方',ty:'题库',f:'部分免费',o:'在线'},
  {t:'蓝桥杯官网（蓝桥OJ）',u:'https://www.lanqiao.cn',d:'蓝桥杯大赛官方：省赛国赛真题、练习系统（本公社内置 168 份题解）',g:1,s:'真题官方',ty:'题库',f:'部分免费',o:'在线'},
  {t:'NOI 全国青少年信息学奥林匹克',u:'https://www.noi.cn',d:'NOI 系列官方：CSP-J/S、NOIP、NOI 历年真题与大纲',g:1,s:'真题官方',ty:'题库·规程',f:'完全免费',o:'可下载'},
  {t:'PTA 拼题A',u:'https://pintia.cn',d:'浙江大学出品 OJ，天梯赛（GPLT）官方平台，教材配套习题',g:1,s:'真题官方',ty:'OJ',f:'完全免费',o:'在线'},
  {t:'ICPC Live Archive',u:'https://onlinejudge.org',d:'UVA/ICPC 历史题库，区域赛与世界总决赛历年题（本公社内置 158 份题解）',g:1,s:'真题官方',ty:'OJ',f:'完全免费',o:'在线'},
  {t:'Competitive Programmer’s Handbook',u:'https://cses.fi/book/book.pdf',d:'Antti Laaksonen 免费英文竞赛教材 PDF（300 页，CSES 系列配套）',g:1,s:'开源书',ty:'书 PDF',f:'完全免费',o:'可下载'},
  {t:'CSES Problem Set',u:'https://cses.fi/problemset/',d:'300 道经典算法题的成体系题集，与上书配套，国际公认刷完即强',g:1,s:'OJ 题库',ty:'题集',f:'完全免费',o:'在线'},
  {t:'代码随想录',u:'https://programmercarl.com',d:'程序员 Carl 的免费算法训练营笔记：刷题路线 + 各专题套路',g:1,s:'训练路线',ty:'题单·笔记',f:'完全免费',o:'可下载'},
  {t:'labuladong 的算法小抄',u:'https://labuladong.online/algo/',d:'框架思维学算法，免费章节覆盖核心套路',g:1,s:'训练路线',ty:'笔记',f:'部分免费',o:'在线'},
  {t:'灵茶山艾府（EndlessCheng）题单',u:'https://github.com/EndlessCheng/codeforces-go',d:'B 站灵神的 Go/Python 题解仓库 + 分专题题单，从零基础到全场第三个做出来',g:1,s:'训练路线',ty:'题单·开源',f:'完全免费',o:'可下载'},
  {t:'洛谷官方题单',u:'https://www.luogu.com.cn/training/list',d:'官方整理的从入门到进阶刷题路线，按知识点分阶',g:1,s:'训练路线',ty:'题单',f:'完全免费',o:'在线'},
  {t:'Codeforces EDU',u:'https://codeforces.com/edu/courses',d:'Codeforces 官方免费课程：二分/线段树/后缀数组等交互式课件',g:1,s:'训练路线',ty:'课程',f:'完全免费',o:'在线'},
  {t:'算法竞赛进阶指南（配套 OJ）',u:'https://www.acwing.com/activity/',d:'李煜东《算法竞赛进阶指南》配套习题与活动（书需自购，OJ 免费）',g:1,s:'开源书',ty:'OJ',f:'部分免费',o:'在线'},
  {t:'Competitive Companion',u:'https://github.com/jmerle/competitive-companion',d:'浏览器插件：一键抓取题目数据到本地，刷题利器',g:1,s:'工具',ty:'工具·开源',f:'完全免费',o:'可下载'},
  {t:'Project Euler',u:'https://projecteuler.net',d:'900+ 道数学向编程题，提交答案值制，重数学洞察轻模板',g:1,s:'数学与思维',ty:'题库',f:'完全免费',o:'在线'},
  {t:'Advent of Code',u:'https://adventofcode.com',d:'每年 12 月的故事化编程解谜活动，历年题目常驻，任选语言',g:1,s:'数学与思维',ty:'题库',f:'完全免费',o:'在线'},
  {t:'Kattis',u:'https://open.kattis.com',d:'瑞典 KTH 运营的 OJ，ICPC 风格题按难度评分，欧美高校训练主力',g:1,s:'数学与思维',ty:'OJ',f:'完全免费',o:'在线'},
  {t:'ICPC 官方历年 World Finals 题',u:'https://icpc.global/worldfinals/past-problems',d:'ICPC 官方历年总决赛题面 PDF 整册下载（公社内置 158 份题解可配套）',g:1,s:'真题官方',ty:'真题PDF',f:'完全免费',o:'可下载'},
  {t:'ICPC Kattis 官方镜像',u:'https://icpc.kattis.com',d:'近年 ICPC 真题官方在线评测镜像',g:1,s:'真题官方',ty:'OJ',f:'完全免费',o:'在线'},
  {t:'Codeforces Gym',u:'https://codeforces.com/gyms',d:'2600+ 场历年 ICPC 区域赛镜像赛，支持虚拟参赛，模拟区域赛节奏',g:1,s:'真题官方',ty:'OJ',f:'完全免费',o:'在线'},
  {t:'卡码网',u:'https://kamacoder.com',d:'代码随想录团队出品：ACM 模式输入输出专项 + 大厂笔试真题风格',g:1,s:'OJ 题库',ty:'OJ',f:'完全免费',o:'在线'},
  {t:'《Algorithms》Jeff Erickson',u:'http://algorithms.wtf',d:'UIUC 教授算法教材官方免费 PDF，质量可比肩 CLRS（英文）',g:1,s:'开源书',ty:'书 PDF',f:'完全免费',o:'可下载'},
  {t:'AtCoder Educational DP Contest',u:'https://atcoder.jp/contests/dp',d:'A~Z 共 26 题的官方 DP 入门经典题组，社区有完整中文题解',g:1,s:'训练路线',ty:'题单',f:'完全免费',o:'在线'},
  {t:'AtCoder Problems',u:'https://kenkoooo.com/atcoder',d:'AtCoder 全题难度 / 标签检索与刷题进度追踪（公社 AtCoder 索引同源）',g:1,s:'训练路线',ty:'题单工具',f:'完全免费',o:'在线'},
  {t:'LC-Rating & Training',u:'https://huxulm.github.io/lc-rating',d:'基于灵茶山艾府题解的力扣竞赛题评分与训练页，按知识点 / 难度刷',g:1,s:'训练路线',ty:'题单工具',f:'完全免费',o:'在线'},
  {t:'灵茶山艾府（B站）',u:'https://space.bilibili.com/226832780',d:'「基础算法精讲」免费视频课：滑动窗口 / 二分 / 链表 / 树 / DP',g:1,s:'训练路线',ty:'视频课',f:'完全免费',o:'App缓存'},
  {t:'KACTL 竞赛模板手册',u:'https://github.com/kth-competitive-programming/kactl',d:'KTH 皇家理工 ICPC 队 C++ 模板，25 页可直接打印的赛场手册 PDF',g:1,s:'工具',ty:'模板库·开源',f:'完全免费',o:'可下载'},
  {t:'TheAlgorithms/C-Plus-Plus',u:'https://github.com/TheAlgorithms/C-Plus-Plus',d:'C++ 算法实现集合（34.7k star），同系列还有 Python / Java 多语言版本',g:1,s:'工具',ty:'算法库·开源',f:'完全免费',o:'可下载'},
  {t:'CP Editor',u:'https://github.com/cpeditor/cpeditor',d:'专为算法竞赛设计的免费编辑器：联动题目解析、一键编译运行调试',g:1,s:'工具',ty:'编辑器·开源',f:'完全免费',o:'可下载'},
  {t:'Testlib 出题对拍库',u:'https://github.com/MikeMirzayanov/testlib',d:'Codeforces 出题 / 对拍事实标准库：checker / interactor / generator',g:1,s:'工具',ty:'工具库·开源',f:'完全免费',o:'可下载'},

  /* ============ 2 升学考试 ============ */
  {t:'中国教育考试网',u:'https://www.neea.edu.cn',d:'教育部教育考试院总入口：高考/研考/四六级/NCRE/教资大纲与试题',g:2,s:'官方考试机构',ty:'官网',f:'完全免费',o:'可下载'},
  {t:'全国大学英语四六级考试官网',u:'https://cet.neea.edu.cn',d:'CET 官方专题：考试大纲、报名、电子成绩报告单免费下载',g:2,s:'官方考试机构',ty:'官网',f:'完全免费',o:'可下载'},
  {t:'NCRE 全国计算机等级考试',u:'https://ncre-bm.neea.cn',d:'计算机一至四级报名入口，大纲科目表在 neea.edu.cn 免费查阅',g:2,s:'官方考试机构',ty:'官网',f:'完全免费',o:'可下载'},
  {t:'中国研究生招生信息网',u:'https://yz.chsi.com.cn',d:'考研官方总平台：专业目录、招生简章、统考网报、调剂与成绩',g:2,s:'官方考试机构',ty:'官网',f:'完全免费',o:'在线'},
  {t:'学信网',u:'https://www.chsi.com.cn',d:'成绩 / 学历 / 学籍查询，考研报名资格关联平台',g:2,s:'官方考试机构',ty:'官网',f:'完全免费',o:'在线'},
  {t:'中小学教师资格考试网',u:'http://ntce.neea.edu.cn',d:'教资《考试标准》《考试大纲》官方免费下载入口',g:2,s:'官方考试机构',ty:'官网',f:'完全免费',o:'可下载'},
  {t:'北京教育考试院',u:'https://www.bjeea.cn',d:'京卷高考真题与答案官方发布，另有中招 / 成考栏目',g:2,s:'各省考试院',ty:'官网',f:'完全免费',o:'可下载'},
  {t:'上海市教育考试院',u:'https://www.shmeea.edu.cn',d:'上海卷高考真题、等级考真题官方发布',g:2,s:'各省考试院',ty:'官网',f:'完全免费',o:'可下载'},
  {t:'广东省教育考试院',u:'https://eea.gd.gov.cn',d:'广东高考 / 学考 / 专升本统考大纲与试题公告',g:2,s:'各省考试院',ty:'官网',f:'完全免费',o:'可下载'},
  {t:'湖北省教育考试院',u:'https://www.hbea.edu.cn',d:'湖北高考真题答案官方发布页',g:2,s:'各省考试院',ty:'官网',f:'完全免费',o:'可下载'},
  {t:'四川省教育考试院',u:'https://www.sceea.cn',d:'四川高考（全国卷）真题答案与招考公告',g:2,s:'各省考试院',ty:'官网',f:'完全免费',o:'可下载'},
  {t:'浙江省教育考试院',u:'https://www.zjzs.net',d:'浙江高考选考真题、专升本大纲与报名',g:2,s:'各省考试院',ty:'官网',f:'完全免费',o:'可下载'},
  {t:'江苏省教育考试院',u:'https://www.jseea.cn',d:'江苏高考真题、专转本实施办法与大纲',g:2,s:'各省考试院',ty:'官网',f:'完全免费',o:'可下载'},
  {t:'山东省教育招生考试院',u:'https://www.sdzk.cn',d:'夏季 / 春季高考、专升本独立专栏，大纲政策权威发布',g:2,s:'各省考试院',ty:'官网',f:'完全免费',o:'可下载'},
  {t:'国家中小学智慧教育平台',u:'https://basic.smartedu.cn',d:'教育部官方：全学段全学科课程（视频+课件+任务单+习题），全部免费',g:2,s:'国家智慧教育平台',ty:'平台',f:'完全免费',o:'App缓存'},
  {t:'智慧教育平台·教材频道',u:'https://basic.smartedu.cn/tchMaterial',d:'正版电子教材在线阅览，覆盖统编 / 人教等 7 社百余册',g:2,s:'国家智慧教育平台',ty:'电子教材',f:'完全免费',o:'在线'},
  {t:'智慧中小学 APP',u:'https://basic.smartedu.cn',d:'官方移动端：名师微课倍速、重点标记、离线缓存——最合规的离线方案',g:2,s:'国家智慧教育平台',ty:'平台APP',f:'完全免费',o:'App缓存'},
  {t:'国家高等教育智慧教育平台',u:'https://higher.smartedu.cn',d:'3.1 万门国家级 / 省级一流本科课程、虚拟仿真实验与电子教材',g:2,s:'国家智慧教育平台',ty:'平台',f:'完全免费',o:'部分可下载'},
  {t:'国家职业教育智慧教育平台',u:'https://vocational.smartedu.cn',d:'职教专业教学资源库、在线精品课、虚拟仿真实训',g:2,s:'国家智慧教育平台',ty:'平台',f:'完全免费',o:'在线'},
  {t:'tchMaterial-parser（开源工具）',u:'https://github.com/search?q=tchMaterial-parser',d:'开源小程序：输入国家平台教材页链接即可合成高清 PDF（注意教材版权）',g:2,s:'国家智慧教育平台',ty:'工具·开源',f:'完全免费',o:'可下载'},
  {t:'人教社中小学教材电子版',u:'https://jc.pep.com.cn',d:'人教社官方电子课本页，人教版各科在线翻页阅览',g:2,s:'电子教材',ty:'电子教材',f:'完全免费',o:'在线'},
  {t:'高教书苑',u:'https://ebook.hep.com.cn',d:'高等教育出版社官方电子书平台，大学教材在线阅览',g:2,s:'电子教材',ty:'电子教材',f:'部分免费',o:'在线'},
  {t:'高教社 ICC 数字课程云平台',u:'https://icc.hep.com.cn',d:'高教社数字教材与配套课程学习平台，大学教材配套资源',g:2,s:'电子教材',ty:'平台',f:'部分免费',o:'在线'},
  {t:'辽宁招生考试之窗·专升本',u:'https://www.lnzsks.com',d:'辽宁专升本官方：考试说明、报名、成绩、录取查询（本公社另有备考助手）',g:2,s:'专升本',ty:'官网·大纲',f:'完全免费',o:'可下载'},
  {t:'广东专插本考试信息网',u:'http://www.gzzkgk.cn',d:'广东专升本资讯站，「省统考大纲和真题」专栏含近年真题回忆',g:2,s:'专升本',ty:'真题·资讯',f:'免费',o:'部分可下载'},
  {t:'易学仕专升本',u:'https://www.hlsok.com',d:'覆盖 20+ 省份的专升本网课与题库 App，有免费资料与免费题库',g:2,s:'专升本',ty:'平台APP',f:'部分免费',o:'App缓存'},
  {t:'库课网校',u:'https://www.kuke99.com',d:'老牌专升本网校 App：直播/点播课、在线题库，公共课部分资源免费',g:2,s:'专升本',ty:'平台APP',f:'部分免费',o:'App缓存'},
  {t:'中国考研网',u:'https://www.chinakaoyan.com',d:'老牌考研门户：政治 / 英语 / 数学历年真题及答案解析汇总',g:2,s:'考研',ty:'真题',f:'免费',o:'可下载'},
  {t:'中国考研网·下载中心',u:'http://download.chinakaoyan.com',d:'按院校 / 省份 / 科目免费下载考研真题：公共课与数百所高校专业课 PDF',g:2,s:'考研',ty:'真题PDF',f:'免费',o:'可下载'},
  {t:'考试点',u:'https://www.kaoshidian.com',d:'1986-2011 考研英语、2003-2013 政治等早年真题及解析下载',g:2,s:'考研',ty:'真题',f:'免费',o:'可下载'},
  {t:'B站·数学汤家凤（官方）',u:'https://space.bilibili.com/search?keyword=%E6%95%B0%E5%AD%A6%E6%B1%A4%E5%AE%B6%E5%87%A4',d:'汤家凤官方空间：高数基础 / 强化全程免费课程，考研数学入门首选',g:2,s:'考研',ty:'视频课',f:'完全免费',o:'App缓存'},
  {t:'B站·张宇/徐涛/腿姐官方号',u:'https://search.bilibili.com/all?keyword=%E8%80%83%E7%A0%94%E6%95%B0%E5%AD%A6%E5%BC%A0%E5%AE%87',d:'站内认准黄 V 官方号：强化班 / 技巧班 / 刷题课大量免费正版内容',g:2,s:'考研',ty:'视频课',f:'完全免费',o:'App缓存'},
  {t:'高校研究生院官网（大纲+真题）',u:'https://yz.neu.edu.cn',d:'示例（东北大学）：自命题科目大纲按教育部要求公开，部分院校附真题样题',g:2,s:'考研',ty:'官网·大纲',f:'完全免费',o:'可下载'},
  {t:'中国教育在线·高考频道',u:'https://gaokao.eol.cn',d:'「历年高考试题及答案」专栏（2018-2025），按科目分类附作文与范文',g:2,s:'高考真题聚合',ty:'真题',f:'免费',o:'可下载'},
  {t:'掌上高考',u:'https://www.gaokao.cn',d:'官方背景 App：查大学 / 专业 / 分数线全免费；公众号可领各省真题 word 版',g:2,s:'高考真题聚合',ty:'平台APP',f:'免费',o:'可下载'},
  {t:'高考直通车',u:'https://www.gaokaozhitongche.com',d:'历年高考真题 + 全国模考联考卷，考后即更新答案，支持下载打印与错题本',g:2,s:'高考真题聚合',ty:'真题·APP',f:'大部分免费',o:'可下载'},
  {t:'百度题库·高考试题套卷库',u:'https://tiku.baidu.com',d:'历年真题 / 一模二模三模 / 名校精品卷，附解析与估分',g:2,s:'高考真题聚合',ty:'题库',f:'大部分免费',o:'可下载'},
  {t:'菁优网',u:'https://www.jyeoo.com',d:'小初高 25 学科试题库，App「免费专区」可下载排好版的试卷，解析完备',g:2,s:'高考真题聚合',ty:'题库',f:'部分免费',o:'可下载'},
  {t:'学科网',u:'https://www.zxxk.com',d:'全国最大中小学教学资源站之一（课件/教案/试题），免费资源每日限额',g:2,s:'高考真题聚合',ty:'题库·资源',f:'少量免费',o:'可下载'},
  {t:'国家平台·课程教学习题',u:'https://basic.smartedu.cn',d:'每个学习节点配「学习任务单 + 课后练习」，官方免费的一课一练式习题',g:2,s:'学科专项',ty:'习题',f:'完全免费',o:'App缓存'},
  {t:'普特英语听力',u:'https://www.putclub.com',d:'老牌免费英语听力站，整理 VOA/BBC/四六级听力材料，国内直连快',g:2,s:'学科专项',ty:'听力',f:'免费',o:'可下载'},
  {t:'赖世雄美语从头学（B站）',u:'https://search.bilibili.com/all?keyword=%E8%B5%96%E4%B8%96%E9%9B%84%E7%BE%8E%E8%AF%AD%E4%BB%8E%E5%A4%B4%E5%AD%A6',d:'经典零基础美语教程（音标→入门→初级）完整免费合集，四六级 / 专升本打基础',g:2,s:'学科专项',ty:'视频课',f:'完全免费',o:'App缓存'},
  {t:'B站·高中理化生实验合集',u:'https://search.bilibili.com/all?keyword=%E9%AB%98%E4%B8%AD%E5%8C%96%E5%AD%A6%E5%AE%9E%E9%AA%8C%E6%BC%94%E7%A4%BA',d:'播放量 10 万+ 的实验课合集，覆盖高考实验考点',g:2,s:'学科专项',ty:'实验视频',f:'完全免费',o:'App缓存'},
  {t:'中国大学先修课 CAP（爱课程）',u:'https://www.icourses.cn',d:'教育部爱课程：近 40 门大学先修课免费开放，高中-大学衔接',g:2,s:'大学衔接',ty:'视频课',f:'完全免费',o:'在线'},
  {t:'MOOC中国（导航站）',u:'https://www.mooc.cn',d:'全球优秀中文 MOOC 课程导航，按学科检索免费开放课程',g:2,s:'大学衔接',ty:'导航站',f:'免费',o:'在线'},

  /* ============ 3 公务员·编制 ============ */
  {t:'国家公务员局',u:'http://www.scs.gov.cn',d:'国考公告、考试大纲、政策法规的法定发布机关官网',g:3,s:'官方渠道',ty:'官网',f:'完全免费',o:'在线'},
  {t:'国考年度专题网站',u:'http://bm.scs.gov.cn/kl2026',d:'中央机关考录专题：公告、大纲、职位表 Excel 下载、报名、查分',g:3,s:'官方渠道',ty:'官网',f:'完全免费',o:'可下载'},
  {t:'中国人事考试网',u:'http://www.cpta.com.cn',d:'人社部人事考试中心官网，职业资格考试与人事考试权威信息',g:3,s:'官方渠道',ty:'官网',f:'完全免费',o:'在线'},
  {t:'人力资源和社会保障部',u:'http://www.mohrss.gov.cn',d:'部委官网，含中央和国家机关所属事业单位公开招聘公告入口',g:3,s:'官方渠道',ty:'官网',f:'完全免费',o:'在线'},
  {t:'三支一扶计划（人社部）',u:'https://chrm.mohrss.gov.cn',d:'各省三支一扶招募公告、政策法规、人才需求目录官方汇总',g:3,s:'官方渠道',ty:'官网',f:'完全免费',o:'在线'},
  {t:'军队人才网',u:'http://81rc.81.cn',d:'军委政治工作部主办：军队文职招考公告、职位表、报名唯一官方渠道',g:3,s:'官方渠道',ty:'官网',f:'完全免费',o:'可下载'},
  {t:'中国政府网',u:'https://www.gov.cn',d:'政府工作报告全文、国务院政策文件库、中央一号文件权威出处',g:3,s:'官方渠道',ty:'官网',f:'完全免费',o:'可下载'},
  {t:'全国人事考试网导航',u:'https://www.rsks.cn',d:'第三方聚合站：31 省人事考试网网址与国省考时间节点汇总',g:3,s:'官方渠道',ty:'导航站',f:'完全免费',o:'在线'},
  {t:'粉笔',u:'https://www.fenbi.com',d:'行测/申论/面试、公基职测等题库，0 元模考大赛与免费小讲堂',g:3,s:'题库 APP',ty:'题库·网课',f:'部分免费',o:'App缓存'},
  {t:'粉笔网页版',u:'https://pc.fenbi.com',d:'官方网页端：分模块刷行测、做真题套卷与模考，手机端同步',g:3,s:'题库 APP',ty:'题库',f:'部分免费',o:'在线'},
  {t:'华图在线',u:'https://v.huatu.com',d:'公职类在线题库：模考大赛、历年真题，覆盖国省考 / 事业单位 / 文职',g:3,s:'题库 APP',ty:'题库',f:'部分免费',o:'App缓存'},
  {t:'华图文档（资料下载）',u:'https://gz.huatu.com',d:'各省真题答案、职位表、成绩排名、面试名单文档下载预览平台',g:3,s:'题库 APP',ty:'资料下载',f:'大部分免费',o:'可下载'},
  {t:'中公教育',u:'http://www.offcn.com',d:'老牌公考机构官网，常年 0 元领：真题汇编、申论范文、专项手册',g:3,s:'题库 APP',ty:'资料站',f:'部分免费',o:'可下载'},
  {t:'步知公考',u:'https://www.buzhi.com',d:'公考在线学习平台：历年套题、专项题库、申论 AI 批改与直播课',g:3,s:'题库 APP',ty:'题库·网课',f:'部分免费',o:'App缓存'},
  {t:'QZZN 公务员考试论坛',u:'https://bbs.qzzn.com',d:'2005 年起的老牌公考社区：申论 / 国考 / 遴选 / 资料分享版块',g:3,s:'题库 APP',ty:'社区论坛',f:'免费(注册)',o:'在线'},
  {t:'粉笔·分模块专项练习',u:'https://www.fenbi.com/spa/tiku/qcat/1',d:'言语 / 判断（图形定义类比逻辑）/ 数量 / 资料 / 常识五模块专项刷题',g:3,s:'行测专项',ty:'题库',f:'部分免费',o:'App缓存'},
  {t:'粉笔·公基1000题官方PDF',u:'https://www.fenbi.com/fpr/doc-user-v2/dir/23369',d:'粉笔官方资料库：事业单位公共基础知识 1000 题 PDF 等免费资料包',g:3,s:'行测专项',ty:'真题PDF',f:'完全免费',o:'可下载'},
  {t:'江苏华图·备考资料0元领',u:'https://js.huatu.com',d:'申论 / 资料 / 言语 / 数量 / 判断 / 常识思维导图免费领（各省站均有）',g:3,s:'行测专项',ty:'资料下载',f:'完全免费',o:'可下载'},
  {t:'人民日报评论',u:'http://opinion.people.com.cn',d:'「人民时评」「评论员文章」合集，申论大作文结构与论证第一素材库',g:3,s:'申论',ty:'官网',f:'完全免费',o:'在线'},
  {t:'新华网·新华时评',u:'http://www.news.cn',d:'新华社「新华时评」「评论员」专栏，语言规范站位高，积累规范表述',g:3,s:'申论',ty:'官网',f:'完全免费',o:'在线'},
  {t:'半月谈网',u:'http://www.banyuetan.org',d:'中宣部委托新华社主办的「中华第一刊」官网，基层治理案例最贴近申论',g:3,s:'申论',ty:'官网',f:'大部分免费',o:'在线'},
  {t:'历年政府工作报告全文',u:'https://www.gov.cn',d:'历年报告全文 + 一图读懂版，申论政策表述与面试热点标准答案库',g:3,s:'申论',ty:'官网',f:'完全免费',o:'可下载'},
  {t:'粉笔申论小讲堂',u:'https://www.fenbi.com',d:'官方免费图文：概括 / 对策 / 公文 / 大作文分题型精讲',g:3,s:'申论',ty:'图文讲义',f:'完全免费',o:'在线'},
  {t:'国务院政策文件库',u:'https://www.gov.cn/zhengce/xxgk/',d:'国务院文件、中央一号文件等中央文件全文检索库',g:3,s:'时政',ty:'官网',f:'完全免费',o:'可下载'},
  {t:'各机构每月时政汇总',u:'https://www.huatu.com',d:'华图 / 粉笔 / 中公每月免费更新的时政热点与考前预测，可领取',g:3,s:'时政',ty:'时政资料',f:'完全免费',o:'可下载'},
  {t:'新华社报刊网·半月谈电子版',u:'http://paper.news.cn',d:'《半月谈》杂志电子版专区，全年各期时政文章，时政 + 申论双用',g:3,s:'时政',ty:'时政',f:'大部分免费',o:'在线'},
  {t:'粉笔面试公开课（B站）',u:'https://search.bilibili.com/all?keyword=%E7%B2%89%E7%AC%94%E9%9D%A2%E8%AF%95',d:'名师结构化面试免费公开课：综合分析 / 计划组织 / 应急应变各题型',g:3,s:'面试',ty:'视频课',f:'完全免费',o:'App缓存'},
  {t:'B站·结构化面试入门（墨迟）',u:'https://search.bilibili.com/all?keyword=%E5%A2%A8%E8%BF%9F%20%E7%BB%93%E6%9E%84%E5%8C%96%E9%9D%A2%E8%AF%95',d:'免费结构化面试入门系列，一道题打通各题型答题框架',g:3,s:'面试',ty:'视频课',f:'完全免费',o:'App缓存'},
  {t:'华图在线·历年真题',u:'https://v.huatu.com/tiku/',d:'国考、各省省考行测申论历年真题在线做题 + 答案解析，可整卷模考',g:3,s:'真题下载',ty:'题库',f:'部分免费',o:'App缓存'},
  {t:'上岸鸭公考',u:'https://www.gwy.com',d:'各省行测真题题库与解析下载，真题分省分类清晰',g:3,s:'真题下载',ty:'题库·真题',f:'大部分免费',o:'可下载'},
  {t:'富尔题库',u:'https://www.ifoor.com',d:'公务员考试历年真题试卷及答案解析，可直接查看 / 下载',g:3,s:'真题下载',ty:'真题PDF',f:'大部分免费',o:'可下载'},
  {t:'我爱真题网·在线题库',u:'https://tiku.woaizhenti.com',d:'考生自发真题分享站：时政一本通、历年国省考真题电子版汇总',g:3,s:'真题下载',ty:'真题PDF',f:'大部分免费',o:'可下载'},
  {t:'全国事业单位招考服务平台',u:'https://www.sydwzl.com',d:'事业单位招考报名平台：报名、准考证、成绩查询',g:3,s:'事业编·基层',ty:'官网',f:'完全免费',o:'在线'},
  {t:'233网校·社区工作者',u:'https://www.233.com',d:'社区工作者笔试报名信息、教材考点与免费试题解析',g:3,s:'事业编·基层',ty:'题库·资讯',f:'部分免费',o:'在线'},
  {t:'中国社工考试网',u:'https://www.zgsqks.com',d:'社会工作者职业资格考试历年考生回忆版真题与答案汇总（初/中级）',g:3,s:'事业编·基层',ty:'真题',f:'大部分免费',o:'可下载'},
  {t:'考考公务员·辅警题库',u:'https://www.kkgwy.com',d:'辅警招聘考试法律知识题库（治安处罚法 / 道交法 / 行政处罚法）',g:3,s:'事业编·基层',ty:'题库',f:'大部分免费',o:'在线'},
  {t:'李梦娇常识速记口诀（B站）',u:'https://search.bilibili.com/all?keyword=%E6%9D%8E%E6%A2%A6%E5%A8%87%20%E5%B8%B8%E8%AF%86%E5%8F%A3%E8%AF%80',d:'华图名师常识 / 公基带背完整版（88 条口诀，数十小时），记忆首选',g:3,s:'免费网课',ty:'视频课',f:'完全免费',o:'App缓存'},
  {t:'刘文超Vin 资料分析（B站）',u:'https://search.bilibili.com/all?keyword=%E5%88%98%E6%96%87%E8%B6%85%20%E8%B5%84%E6%96%99%E5%88%86%E6%9E%90',d:'B 站公考圈口碑最高的免费资料分析 / 数量关系系统班，速算技巧全免费',g:3,s:'免费网课',ty:'视频课',f:'完全免费',o:'App缓存'},
  {t:'公考邵书阳 言语理解（B站）',u:'https://search.bilibili.com/all?keyword=%E5%85%AC%E8%80%83%E9%82%B5%E4%B9%A6%E9%98%B3',d:'言语理解与表达系统讲解与真题带刷，行测言语模块免费课代表',g:3,s:'免费网课',ty:'视频课',f:'完全免费',o:'App缓存'},
  {t:'B站·系统公考教程198集',u:'https://search.bilibili.com/all?keyword=%E5%85%AC%E5%8A%A1%E5%91%98%20%E7%B3%BB%E7%BB%9F%E6%95%99%E7%A8%8B',d:'全流程公考自学教程：行测 + 申论手把手教学，零基础搭框架',g:3,s:'免费网课',ty:'视频课',f:'完全免费',o:'App缓存'},

  /* ============ 4 红色经典·人文古籍 ============ */
  {t:'中文马克思主义文库',u:'https://www.marxists.org/chinese/',d:'《马恩全集》《列宁全集》《斯大林全集》《共产党宣言》等中文全文库（直连不稳）',g:4,s:'马列文献',ty:'全文库',f:'完全免费',o:'可下载',w:1},
  {t:'理论中国·电子书库',u:'https://ebook.theorychina.org.cn',d:'中央党史和文献研究院旗下电子书库：马列经典、党章及领袖著作电子版',g:4,s:'马列文献',ty:'全文库',f:'免费(注册)',o:'在线'},
  {t:'共产党员网（12371）',u:'https://www.12371.cn',d:'中组部主办：党章党规、党史、《共产党宣言》全文、课件下载专栏',g:4,s:'党史平台',ty:'全文库·课件',f:'完全免费',o:'可下载'},
  {t:'人民网·党史频道',u:'http://dangshi.people.cn',d:'党史百科、经典著作、党史大事记、历次党代会文献、党史上的今天',g:4,s:'党史平台',ty:'文献库',f:'完全免费',o:'在线'},
  {t:'中国共产党新闻网',u:'https://cpc.people.com.cn',d:'党章历次修订全文、领导人著作与讲话、领导人纪念文库',g:4,s:'党史平台',ty:'新闻·文献库',f:'完全免费',o:'在线'},
  {t:'中央党史和文献研究院',u:'https://www.dswxyjy.org.cn',d:'权威党史文献发布，《中共党史研究》《党的文献》等院办期刊文章',g:4,s:'党史平台',ty:'文献库',f:'完全免费',o:'在线'},
  {t:'求是网',u:'https://www.qstheory.cn',d:'中央党刊《求是》全部文章全文，重要著作与讲话全文专栏',g:4,s:'党史平台',ty:'全文库',f:'完全免费',o:'在线'},
  {t:'学习强国',u:'https://www.xuexi.cn',d:'中宣部平台：马恩列全集分卷电子书、党史慕课、视听学习与挑战答题',g:4,s:'党史平台',ty:'全文库·视听',f:'完全免费',o:'App缓存'},
  {t:'毛泽东著作专页（马库）',u:'https://www.marxists.org/chinese/maozedong/index.htm',d:'《毛泽东选集》1-5 卷、早期文稿、诗词全文——与公社内置 229 篇可互校（直连不稳）',g:4,s:'领袖著作',ty:'全文库',f:'完全免费',o:'可下载',w:1},
  {t:'习近平著作选读专栏（共产党员网）',u:'https://www.12371.cn',d:'《习近平著作选读》《习近平谈治国理政》等官方全文及视频课件',g:4,s:'领袖著作',ty:'全文库',f:'完全免费',o:'可下载'},
  {t:'央视网纪实台（片库）',u:'https://jishi.cctv.com',d:'《国家记忆》《红色传奇》《信仰的力量》《美术经典中的党史》免费点播',g:4,s:'红色影像',ty:'影像',f:'完全免费',o:'App缓存'},
  {t:'1905 电影网',u:'https://www.1905.com',d:'CCTV-6 官方平台，正版免费经典老片 / 红色电影专区',g:4,s:'红色影像',ty:'影像',f:'部分免费',o:'App缓存'},
  {t:'延安革命纪念馆',u:'https://www.1937china.com',d:'中共中央在延安十三年专题纪念馆，11 万件藏品介绍与网上数字展馆',g:4,s:'红色影像',ty:'云展馆',f:'完全免费',o:'在线'},
  {t:'中国哲学书电子化计划',u:'https://ctext.org/zh',d:'最大开源古籍库之一：先秦至清经典全文检索 + 四库全书影印，含二十四史',g:4,s:'古籍库',ty:'全文库·检索',f:'完全免费',o:'可下载'},
  {t:'汉典',u:'https://www.zdic.net',d:'10 万+ 汉字、60 万+ 词语检索，附《说文》《康熙》引证；子站古籍 / 诗词',g:4,s:'古籍库',ty:'检索工具',f:'完全免费',o:'在线'},
  {t:'国学大师',u:'http://www.guoxuedashi.net',d:'古籍全文检索 + 影印 + TXT 下载，经史子集分类齐全',g:4,s:'古籍库',ty:'全文库·检索',f:'完全免费',o:'可下载'},
  {t:'识典古籍',u:'https://www.shidianguji.com',d:'北大 × 字节跳动共建：4.7 万部古籍免费开放，简繁转换、OCR、AI 整理',g:4,s:'古籍库',ty:'全文库',f:'免费(注册)',o:'在线'},
  {t:'国家图书馆·中华古籍资源库',u:'https://guji.nlc.cn',d:'善本 / 碑帖 / 甲骨 / 敦煌遗书高清影像，2021 年底起免登录浏览',g:4,s:'古籍库',ty:'影像库',f:'完全免费',o:'在线'},
  {t:'书格',u:'https://shuge.org',d:'公版古籍 / 书画 / 碑帖 / 舆图高清彩色扫描，来自世界各地图书馆，直链下载',g:4,s:'古籍库',ty:'影像库',f:'完全免费',o:'可下载'},
  {t:'殆知阁古代文献',u:'https://daizhige.org',d:'1.6 万余种、约 20 亿字古籍纯文本；GitHub 整库镜像，最佳离线古籍源',g:4,s:'古籍库',ty:'全文库',f:'完全免费',o:'可下载'},
  {t:'文渊阁四库全书全文（殆知阁）',u:'https://sikuquanshu.daizhige.org',d:'殆知阁旗下《四库全书》电子全文站点',g:4,s:'古籍库',ty:'全文库',f:'完全免费',o:'可下载'},
  {t:'漢川草廬',u:'http://www.sidneyluo.net',d:'繁体《十三经》《二十四史》《资治通鉴》294 卷全文在线',g:4,s:'古籍库',ty:'全文库',f:'完全免费',o:'可下载'},
  {t:'国学网',u:'http://www.guoxue.com',d:'老牌国学学术站：经部 / 史部原典、学术动态与论文',g:4,s:'古籍库',ty:'全文库·学术',f:'完全免费',o:'在线'},
  {t:'数字敦煌',u:'https://www.e-dunhuang.com',d:'敦煌研究院官方：30+ 经典洞窟高清全景漫游、壁画细节、藏经洞文献检索',g:4,s:'古籍库',ty:'影像库',f:'完全免费',o:'在线'},
  {t:'中华经典古籍库',u:'https://gj.ancientbooks.cn',d:'中华书局点校本 / 校注本古籍（保留校勘记），个人注册可读部分免费资源',g:4,s:'古籍库',ty:'全文库',f:'部分免费',o:'在线'},
  {t:'中文维基文库',u:'https://zh.wikisource.org',d:'458 万+ 篇公版中文文献（典籍、史书、法律、民国文献），CC 协议（需国际网络）',g:4,s:'文库',ty:'全文库',f:'完全免费',o:'可下载',w:1},
  {t:'古腾堡计划·中文书架',u:'https://www.gutenberg.org/browse/languages/zh',d:'7.5 万+ 公版电子书：古籍、民国中译名著、鲁迅《阿Q正传》等，txt/EPUB 直下',g:4,s:'文库',ty:'全文库',f:'完全免费',o:'可下载',w:1},
  {t:'台湾华文电子书园地',u:'https://taiwanebook.ncl.edu.tw',d:'台湾国图公版书在线翻阅平台，含民国旧籍影印',g:4,s:'文库',ty:'影像库',f:'完全免费',o:'在线',w:1},
  {t:'北京鲁迅博物馆·著作全编检索',u:'http://cx.luxunmuseum.com.cn',d:'官方「鲁迅著作全编」：文章浏览 + 简单 / 高级检索，可验证「鲁迅说过的话」',g:4,s:'文学经典',ty:'全文库·检索',f:'完全免费',o:'在线'},
  {t:'鲁迅全集在线（马库版）',u:'https://www.marxists.org/chinese/reference-books/luxun/index.htm',d:'《呐喊》《彷徨》《野草》、13 部杂文集、《中国小说史略》等分卷全文',g:4,s:'文学经典',ty:'全文库',f:'完全免费',o:'可下载',w:1},
  {t:'搜韵网',u:'https://sou-yun.cn',d:'85 万+ 首古今诗词（含全唐诗 / 全宋词）检索，格律校验与韵典、词谱曲谱',g:4,s:'诗词检索',ty:'全文库·检索',f:'部分免费',o:'在线'},
  {t:'诗词吾爱网',u:'https://www.52shici.com',d:'诗词格律自动检测、创作交流社区，工具型网站',g:4,s:'诗词检索',ty:'检索工具',f:'完全免费',o:'在线'},
  {t:'古诗文网（古文岛）',u:'https://www.gushiwen.cn',d:'最全古诗文站：部编版必背篇目全收录，译文注释赏析与朗诵音频、PDF 下载',g:4,s:'诗词检索',ty:'全文库',f:'完全免费',o:'可下载'},
  {t:'可可诗词网',u:'https://www.kekeshici.com',d:'唐诗宋词名句出处、全诗、注释与赏析，逐句查证友好',g:4,s:'诗词检索',ty:'全文库',f:'完全免费',o:'在线'},
  {t:'国际敦煌项目 IDP',u:'https://idp.bl.uk',d:'大英图书馆牵头的多国馆藏丝路写本 / 绘画高清数字库，学术级（境外较慢）',g:4,s:'古籍库',ty:'影像库',f:'完全免费',o:'部分可下载',w:1},

  /* ============ 5 开放课程·电子书 ============ */
  {t:'中国大学MOOC',u:'https://www.icourse163.org',d:'高教社 × 网易联办，国内最大中文慕课平台，数千门名校课程学习免费',g:5,s:'国内MOOC',ty:'MOOC',f:'部分免费',o:'App缓存'},
  {t:'学堂在线',u:'https://www.xuetangx.com',d:'清华大学发起的慕课平台，1900+ 门课程，多数视频免费看',g:5,s:'国内MOOC',ty:'MOOC',f:'部分免费',o:'App缓存'},
  {t:'智慧树网',u:'https://www.zhihuishu.com',d:'全球最大学分课程运营平台，跨校共享学分课对高校免费开放',g:5,s:'国内MOOC',ty:'MOOC',f:'部分免费',o:'在线'},
  {t:'超星尔雅 / 学习通',u:'http://erya.mooc.chaoxing.com',d:'通识教育平台，人文社科通识课丰富，学习通支持缓存',g:5,s:'国内MOOC',ty:'MOOC',f:'部分免费',o:'App缓存'},
  {t:'好大学在线 CNMOOC',u:'https://cnmooc.sjtu.edu.cn',d:'上海交通大学主办慕课平台，课程学习阶段免费，多校学分互认',g:5,s:'国内MOOC',ty:'MOOC',f:'部分免费',o:'在线'},
  {t:'学银在线',u:'https://www.xueyinonline.com',d:'超星「学分银行」慕课平台，免费注册学习，支持学分转换',g:5,s:'国内MOOC',ty:'MOOC',f:'部分免费',o:'App缓存'},
  {t:'网易云课堂',u:'https://study.163.com',d:'网易旗下实用技能学习平台，大量免费微专业与 IT / 职场入门课',g:5,s:'国内MOOC',ty:'技能课程',f:'部分免费',o:'App缓存'},
  {t:'Coursera',u:'https://www.coursera.org',d:'全球最大 MOOC 之一，绝大多数课程点 Audit/旁听 免费学（需国际网络）',g:5,s:'国际MOOC',ty:'MOOC',f:'部分免费',o:'App缓存',w:1},
  {t:'edX',u:'https://www.edx.org',d:'MIT / 哈佛创办的非营利 MOOC，Audit 通道免费访问课程内容（需国际网络）',g:5,s:'国际MOOC',ty:'MOOC',f:'部分免费',o:'在线',w:1},
  {t:'MIT OpenCourseWare',u:'https://ocw.mit.edu',d:'MIT 2400+ 门课程讲义、作业、考试、视频永久免费，无需注册（需国际网络）',g:5,s:'国际MOOC',ty:'开放课程',f:'完全免费',o:'可下载',w:1},
  {t:'可汗学院（中文版）',u:'https://zh.khanacademy.org',d:'学前至大学早期免费世界级课程，官网自带中文界面，练习 + 视频一体',g:5,s:'国际MOOC',ty:'MOOC·教材',f:'完全免费',o:'App缓存',w:1},
  {t:'FutureLearn',u:'https://www.futurelearn.com',d:'英国开放大学创办的 MOOC 平台，人文社科见长（开课期免费）',g:5,s:'国际MOOC',ty:'MOOC',f:'部分免费',o:'在线',w:1},
  {t:'Saylor Academy',u:'https://www.saylor.org',d:'美国非营利组织，全部自学课程免费无期限，31+ 门课可转大学学分',g:5,s:'国际MOOC',ty:'MOOC·教材',f:'完全免费',o:'可下载',w:1},
  {t:'LibreTexts',u:'https://libretexts.org',d:'全球最大 OER 开放教材库之一，数百本大学级开放教材覆盖理工医（需国际网络）',g:5,s:'开放教材',ty:'教材库',f:'完全免费',o:'可下载',w:1},
  {t:'OpenStax',u:'https://openstax.org',d:'莱斯大学旗下经同行评审的开放正版大学教材，官网直接下载 PDF（需国际网络）',g:5,s:'开放教材',ty:'教材库',f:'完全免费',o:'可下载',w:1},
  {t:'Open Textbook Library',u:'https://open.umn.edu/opentextbooks',d:'明尼苏达大学维护的开放教材库，千余本可自由使用改编（需国际网络）',g:5,s:'开放教材',ty:'教材库',f:'完全免费',o:'可下载',w:1},
  {t:'国家数字图书馆',u:'https://www.nlc.cn',d:'国家级数字资源门户，凭身份证在线免费办读者卡，远程访问电子书 / 期刊库',g:5,s:'电子书·数字图书馆',ty:'书库',f:'免费(注册)',o:'部分可下载'},
  {t:'中华古籍资源库（老入口）',u:'http://read.nlc.cn',d:'国图 10 万部/件善本、敦煌文献、碑帖高清影像，免登录阅览',g:5,s:'电子书·数字图书馆',ty:'书库·古籍',f:'完全免费',o:'在线'},
  {t:'浙江图书馆',u:'https://www.zjlib.cn',d:'支付宝搜「浙江图书馆」免费办证，可远程访问知网等商业数据库与正版电子书',g:5,s:'电子书·数字图书馆',ty:'书库',f:'免费(注册)',o:'部分可下载'},
  {t:'全国图书馆参考咨询联盟',u:'http://www.ucdrs.superlib.net',d:'公益性文献传递平台：检索图书 / 论文后免费邮箱送达章节扫描件',g:5,s:'电子书·数字图书馆',ty:'书库·学术',f:'完全免费',o:'可下载'},
  {t:'微信读书',u:'https://weread.qq.com',d:'正版电子书 + 有声书平台；公版书免费，时长 / 组队可兑换免费读全场',g:5,s:'电子书·数字图书馆',ty:'书库APP',f:'部分免费',o:'App缓存'},
  {t:'上海图书馆',u:'https://www.library.sh.cn',d:'一卡通注册免费，数字资源丰富，读者证可在 OverDrive 借阅电子书',g:5,s:'电子书·数字图书馆',ty:'书库',f:'免费(注册)',o:'部分可下载'},
  {t:'广州数字图书馆',u:'https://www.gzlib.gov.cn',d:'广州「图书馆之城」统一服务平台，注册后免费使用大量数字资源库',g:5,s:'电子书·数字图书馆',ty:'书库',f:'免费(注册)',o:'部分可下载'},
  {t:'国家哲学社会科学文献中心',u:'https://www.ncpssd.org',d:'中国社科院承建：2000+ 种中文学术期刊、1000 多万篇论文免费全文 PDF',g:5,s:'学术资源',ty:'学术库',f:'免费(注册)',o:'可下载'},
  {t:'PubScholar 公益学术平台',u:'https://pubscholar.cn',d:'中科院文献情报中心：1.7 亿条元数据、8000 多万篇可免费获取全文',g:5,s:'学术资源',ty:'学术库',f:'完全免费',o:'可下载'},
  {t:'中国科技论文在线',u:'https://www.paper.edu.cn',d:'教育部科技发展中心主办：首发论文 + 国内最大免费全文期刊库',g:5,s:'学术资源',ty:'学术库',f:'完全免费',o:'可下载'},
  {t:'arXiv',u:'https://arxiv.org',d:'全球最大预印本库，物理 / 数学 / 计算机最新成果免费 PDF（可用 cn.arxiv.org 镜像）',g:5,s:'学术资源',ty:'学术库',f:'完全免费',o:'可下载'},
  {t:'Semantic Scholar',u:'https://www.semanticscholar.org',d:'AI 学术搜索引擎，2 亿+ 论文免费检索与引文分析（需国际网络）',g:5,s:'学术资源',ty:'学术检索',f:'完全免费',o:'可下载',w:1},
  {t:'百度学术',u:'https://xueshu.baidu.com',d:'免费学术搜索，海量中英文文献聚合，标注免费 / 收费来源',g:5,s:'学术资源',ty:'学术检索',f:'完全免费',o:'部分可下载'},
  {t:'AMiner',u:'https://www.aminer.cn',d:'清华计算机系研发的 AI 学术平台：3.2 亿论文 / 专利 + 学者图谱',g:5,s:'学术资源',ty:'学术检索',f:'完全免费',o:'部分可下载'},
  {t:'国家科技图书文献中心 NSTL',u:'https://www.nstl.gov.cn',d:'公益文献传递：外文科技文献低价 / 免费获取，邮件送达',g:5,s:'学术资源',ty:'学术库',f:'部分免费',o:'可下载'},
  {t:'网易公开课',u:'https://open.163.com',d:'15000+ 集免费课程：名校课 / 中国大学公开课 / 可汗学院 / TED 中文字幕',g:5,s:'公开课视频',ty:'公开课',f:'大部分免费',o:'App缓存'},
  {t:'B站·高校官方号与知识区',u:'https://www.bilibili.com',d:'清华 / 北大 / 复旦等官方号入驻，海量公开课、讲座与知识科普，可缓存',g:5,s:'公开课视频',ty:'公开课',f:'完全免费',o:'App缓存'},
  {t:'TED（官网）',u:'https://www.ted.com',d:'数千个科技 / 人文 / 教育演讲免费看，多数有中文志愿字幕，官网可下 MP4',g:5,s:'公开课视频',ty:'公开课',f:'完全免费',o:'可下载',w:1},
  {t:'央视网纪录片片库',u:'https://tv.cctv.com/lm/jl/',d:'《国家记忆》《航拍中国》等大量自制纪录片官方免费在线点播',g:5,s:'公开课视频',ty:'纪录片',f:'完全免费',o:'在线'},
  {t:'BBC Learning English',u:'https://www.bbc.co.uk/learningenglish',d:'六分钟英语等系统栏目，每集配 worksheet、测验和 transcript（需国际网络）',g:5,s:'语言学习',ty:'英语听力',f:'完全免费',o:'可下载',w:1},
  {t:'VOA 慢速英语',u:'https://learningenglish.voanews.com',d:'语速 2/3、词汇 1500 级的分级英语课程 + 测验，附文稿（需国际网络）',g:5,s:'语言学习',ty:'英语听力',f:'完全免费',o:'可下载',w:1},
  {t:'中国日报网英语点津',u:'https://language.chinadaily.com.cn',d:'中国日报官方英语频道：双语新闻 + 听力音频下载，大陆直连',g:5,s:'语言学习',ty:'英语学习',f:'完全免费',o:'可下载'},
  {t:'每日英语听力',u:'https://www.eudic.net',d:'欧路旗下听力库：海量分级听力 + 每日更新，基础功能免费',g:5,s:'语言学习',ty:'听力APP',f:'部分免费',o:'App缓存'},
  {t:'沪江网校 / CCtalk',u:'https://www.cctalk.com',d:'多语种课程平台：公开课免费，覆盖英日韩法德等',g:5,s:'语言学习',ty:'课程平台',f:'部分免费',o:'App缓存'},
  {t:'雅思官方免费备考资料',u:'https://takeielts.britishcouncil.org/take-ielts/prepare',d:'British Council 免费练习卷、答题纸、题目与答案下载',g:5,s:'语言学习',ty:'应试资料',f:'完全免费',o:'可下载',w:1},
  {t:'托福官方中文站',u:'https://www.toefl.cn',d:'ETS 官方中文网站：考试介绍 + 官方免费备考资源入口',g:5,s:'语言学习',ty:'应试资料',f:'部分免费',o:'在线'},
  {t:'多邻国 Duolingo',u:'https://www.duolingo.cn',d:'全球用户最多的免费语言学习 APP，40+ 语种游戏化闯关，中文界面',g:5,s:'语言学习',ty:'语言APP',f:'部分免费',o:'在线'},
  {t:'Code.org',u:'https://code.org',d:'K-12 计算机科学免费课程与「编程一小时」，页面可切简体中文',g:5,s:'少儿编程·启蒙',ty:'少儿编程',f:'完全免费',o:'在线',w:1},
  {t:'Scratch 官方',u:'https://scratch.mit.edu',d:'MIT 出品 6 岁+ 图形化积木编程社区，官方简体中文，离线编辑器可下载',g:5,s:'少儿编程·启蒙',ty:'少儿编程',f:'完全免费',o:'可下载'},
  {t:'可汗学院儿童版',u:'https://learn.khanacademy.org/khan-academy-kids/',d:'2-8 岁完全免费无广告启蒙 APP：数学 / 阅读 / 逻辑，可离线使用',g:5,s:'少儿编程·启蒙',ty:'启蒙APP',f:'完全免费',o:'可下载',w:1},
  {t:'国家智慧教育读书平台',u:'https://reading.smartedu.cn',d:'教育部官方读书平台：中小学好书推荐、经典阅读与有声资源',g:5,s:'少儿编程·启蒙',ty:'阅读平台',f:'完全免费',o:'App缓存'},
  {t:'金山打字通在线版',u:'https://www.dazima.cn',d:'官方在线版：中英文打字练习与速度测试，含指法课程与打字游戏',g:5,s:'综合素养',ty:'打字练习',f:'完全免费',o:'在线'},
  {t:'WPS 学堂',u:'https://www.wps.cn/learning',d:'金山办公官方免费平台：1000+ Office 视频教程（表格函数 / 排版 / 演示）',g:5,s:'综合素养',ty:'办公技能',f:'完全免费',o:'在线'},
  {t:'Microsoft 365 官方培训',u:'https://support.microsoft.com/zh-cn/training',d:'微软官方 Word / Excel / PowerPoint 免费入门教程与快速入门视频',g:5,s:'综合素养',ty:'办公技能',f:'完全免费',o:'可下载'},
  {t:'剪映官方教程',u:'https://www.capcut.cn',d:'剪映官网免费新手指南：剪辑界面、时间线、特效、字幕、导出全流程',g:5,s:'综合素养',ty:'剪辑技能',f:'完全免费',o:'在线'},
  {t:'光影魔术手',u:'https://www.neoimaging.cn',d:'免费修图软件官方站：AI 抠图 / 美容 / 批处理 / 证件照排版',g:5,s:'综合素养',ty:'摄影修图',f:'完全免费',o:'可下载'},

  /* ============ 6 编程·IT·工具 ============ */
  {t:'Python 官方中文文档',u:'https://docs.python.org/zh-cn/3/tutorial/',d:'Python 官方入门教程简体中文版，社区协作翻译、内容最新最权威',g:6,s:'官方文档',ty:'文档',f:'完全免费',o:'可下载'},
  {t:'MDN Web Docs 中文',u:'https://developer.mozilla.org/zh-CN/',d:'Mozilla Web 标准权威文档（HTML/CSS/JS/WebAPI），CC 协议开放',g:6,s:'官方文档',ty:'文档',f:'完全免费',o:'可下载'},
  {t:'Go 语言之旅（中文）',u:'https://tour.go-zh.org/',d:'Go 官方交互式教程中文版，浏览器内直接运行 Go 代码',g:6,s:'官方文档',ty:'教程',f:'完全免费',o:'在线'},
  {t:'Rust 程序设计语言（中文版）',u:'https://kaisery.github.io/trpl-zh-cn/',d:'Rust 官方 The Book 中译本（KaiserY），官方认可',g:6,s:'官方文档',ty:'开源书',f:'完全免费',o:'可下载'},
  {t:'cppreference 中文',u:'https://zh.cppreference.com/',d:'C/C++ 标准参考手册官方中文 Wiki，最权威 C/C++ 查阅站，有离线存档',g:6,s:'官方文档',ty:'文档',f:'完全免费',o:'可下载'},
  {t:'Pro Git 第二版（中文）',u:'https://git-scm.com/book/zh/v2',d:'Git 官方书中文版，开源版权，官网直接下载 PDF/EPUB',g:6,s:'官方文档',ty:'开源书',f:'完全免费',o:'可下载'},
  {t:'Kubernetes 中文文档',u:'https://kubernetes.io/zh-cn/docs/',d:'K8s 官方简体中文文档：概念 / 任务 / 教程 / 参考齐全',g:6,s:'官方文档',ty:'文档',f:'完全免费',o:'可下载'},
  {t:'Docker——从入门到实践',u:'https://docker-practice.github.io/',d:'国内最流行 Docker 开源中文教程（yeasy），有国内镜像',g:6,s:'官方文档',ty:'开源书',f:'完全免费',o:'可下载'},
  {t:'Redis 中文文档',u:'https://redis.cn/',d:'Redis 命令与教程中文站，国内查阅 Redis 的事实标准',g:6,s:'官方文档',ty:'文档',f:'完全免费',o:'在线'},
  {t:'Nginx 中文文档',u:'https://nginx.github.net.cn/',d:'Nginx 官方文档中文翻译（安装 / 配置 / 原理）',g:6,s:'官方文档',ty:'文档',f:'完全免费',o:'可下载'},
  {t:'菜鸟教程',u:'https://www.runoob.com/',d:'中文最全编程入门教程站：全栈语言 + 在线实例即改即运行',g:6,s:'学习平台',ty:'教程站',f:'完全免费',o:'在线'},
  {t:'菜鸟工具（jyshare）',u:'https://www.jyshare.com/',d:'在线工具集合：20+ 语言在线编译、JSON、正则、SQL 等',g:6,s:'学习平台',ty:'工具集',f:'完全免费',o:'在线'},
  {t:'W3School 中文',u:'https://www.w3school.com.cn/',d:'经典 Web 开发中文教程（HTML/CSS/JS/SQL），配在线测试',g:6,s:'学习平台',ty:'教程站',f:'完全免费',o:'在线'},
  {t:'freeCodeCamp 中文',u:'https://www.freecodecamp.org/chinese/',d:'全球最大非营利编程学习平台官方中文站：交互课程 + 免费认证',g:6,s:'学习平台',ty:'平台',f:'完全免费',o:'可下载'},
  {t:'Exercism',u:'https://exercism.org/',d:'83 种语言、8700+ 练习 + 免费人工导师辅导，界面有简体中文',g:6,s:'学习平台',ty:'练习平台',f:'完全免费',o:'在线'},
  {t:'Kaggle Learn',u:'https://www.kaggle.com/learn/',d:'Kaggle 官方免费微课：Python / Pandas / 机器学习 / 深度学习',g:6,s:'学习平台',ty:'课程',f:'完全免费',o:'部分可下载'},
  {t:'CS-Notes',u:'https://github.com/CyC2018/CS-Notes',d:'技术面试基础：算法 / 操作系统 / 网络 / 数据库，可 clone 打印',g:6,s:'开源书与知识库',ty:'知识库·开源',f:'完全免费',o:'可下载'},
  {t:'JavaGuide',u:'https://javaguide.cn/',d:'GitHub 星标最高的 Java 学习 + 面试指南',g:6,s:'开源书与知识库',ty:'知识库·开源',f:'完全免费',o:'可下载'},
  {t:'小林 coding',u:'https://xiaolincoding.com/',d:'图解网络 / 操作系统 / MySQL / Redis，1500 图 100 万字免费阅读',g:6,s:'开源书与知识库',ty:'开源书',f:'完全免费',o:'可下载'},
  {t:'free-programming-books 中文版',u:'https://github.com/EbookFoundation/free-programming-books/blob/main/books/free-programming-books-zh.md',d:'GitHub 最著名免费编程书索引的中文分册，海量合法免费书',g:6,s:'开源书与知识库',ty:'书单·开源',f:'完全免费',o:'可下载'},
  {t:'免费编程中文书籍索引',u:'https://github.com/justjavac/free-programming-books-zh_CN',d:'justjavac 维护的中文免费编程书经典索引',g:6,s:'开源书与知识库',ty:'书单·开源',f:'完全免费',o:'可下载'},
  {t:'Awesome Cheatsheets（中文）',u:'https://github.com/skywind3000/awesome-cheatsheets',d:'各语言 / 工具速查表合集，一页纸复习利器',g:6,s:'开源书与知识库',ty:'速查表·开源',f:'完全免费',o:'可下载'},
  {t:'roadmap.sh（开发者路线图）',u:'https://roadmap.sh/',d:'30+ 开发者职业路线图（前端/后端/DevOps），交互式技能树（有中文社区翻译）',g:6,s:'开源书与知识库',ty:'路线图',f:'完全免费',o:'可下载'},
  {t:'SQLZoo（中文）',u:'https://sqlzoo.net/wiki/SQL_Tutorial/zh',d:'交互式 SQL 在线练习，中文版，边学边在浏览器写 SQL',g:6,s:'数据库与AI',ty:'练习',f:'完全免费',o:'在线'},
  {t:'SQLBolt',u:'https://sqlbolt.com/',d:'零基础交互式 SQL 教程，无需注册，每课配在线练习',g:6,s:'数据库与AI',ty:'练习',f:'完全免费',o:'在线'},
  {t:'牛客网 SQL 题库',u:'https://www.nowcoder.com/',d:'250+ 道 SQL 题在线判题（入门 / 必知必会 / 进阶 / 大厂真题）',g:6,s:'数据库与AI',ty:'题库',f:'免费(注册)',o:'在线'},
  {t:'飞桨 PaddlePaddle',u:'https://www.paddlepaddle.org.cn/',d:'国产深度学习框架官方中文教程、API 文档与新手入门',g:6,s:'数据库与AI',ty:'文档',f:'完全免费',o:'可下载'},
  {t:'飞桨 AI Studio 星河社区',u:'https://aistudio.baidu.com/',d:'免费 GPU 算力 + 在线 Notebook + 免费 AI 实战课程',g:6,s:'数据库与AI',ty:'实验平台',f:'完全免费',o:'在线'},
  {t:'PyTorch 中文文档',u:'https://pytorch.cadn.net.cn/',d:'PyTorch 官方教程与 API 中文翻译（社区维护）',g:6,s:'数据库与AI',ty:'文档',f:'完全免费',o:'可下载'},
  {t:'动手学深度学习（d2l）',u:'https://zh.d2l.ai/',d:'李沐 PyTorch 中文开源教材，B 站配套视频，公认中文深度学习第一书，免费 PDF',g:6,s:'数据库与AI',ty:'开源书',f:'完全免费',o:'可下载'},
  {t:'Datawhale 南瓜书',u:'https://datawhalechina.github.io/pumpkin-book/',d:'周志华《机器学习》（西瓜书）公式逐个推导详解，开源免费',g:6,s:'数据库与AI',ty:'开源书',f:'完全免费',o:'可下载'},
  {t:'Datawhale 组队学习',u:'https://github.com/datawhalechina/',d:'免费开源 AI 课程 + 15~21 天组队打卡学习（吃瓜教程 / joyrl 等）',g:6,s:'数据库与AI',ty:'课程·开源',f:'完全免费',o:'可下载'},
  {t:'李宏毅机器学习（台大）',u:'https://speech.ee.ntu.edu.tw/~hylee/ml/2022-spring.php',d:'中文授课机器学习 / 深度学习全课程，讲义 + 作业免费；B 站可直连观看',g:6,s:'数据库与AI',ty:'课程·讲义',f:'完全免费',o:'可下载'},
  {t:'draw.io / diagrams.net',u:'https://app.diagrams.net/',d:'全能免费绘图（流程图 / 架构图），界面可中文，数据本地存储，桌面版离线',g:6,s:'在线工具',ty:'绘图工具',f:'完全免费',o:'可下载'},
  {t:'Excalidraw',u:'https://excalidraw.com/',d:'手绘风格白板 / 示意图，支持中文，开源可自托管',g:6,s:'在线工具',ty:'绘图工具',f:'完全免费',o:'可下载'},
  {t:'Mermaid Live Editor',u:'https://mermaid.live/',d:'用代码画流程图 / 时序图 / 甘特图，实时预览导出',g:6,s:'在线工具',ty:'绘图工具',f:'完全免费',o:'可下载'},
  {t:'ProcessOn',u:'https://www.processon.com/',d:'中文在线流程图 / 思维导图 / 白板，实时协作（免费版限 9 文件）',g:6,s:'在线工具',ty:'绘图工具',f:'部分免费',o:'在线'},
  {t:'iLovePDF',u:'https://www.ilovepdf.com/zh-cn',d:'PDF 合并 / 拆分 / 压缩 / 转换全家桶，有中文站',g:6,s:'在线工具',ty:'文档工具',f:'大部分免费',o:'在线'},
  {t:'TinyPNG',u:'https://tinypng.com/',d:'PNG/JPEG 智能有损压缩，图片瘦身神器',g:6,s:'在线工具',ty:'图片工具',f:'完全免费',o:'在线'},
  {t:'LaTeX 公式编辑器 latexlive',u:'https://www.latexlive.com/',d:'中文在线 LaTeX 公式编辑，实时预览 + 图片识别公式',g:6,s:'在线工具',ty:'公式工具',f:'完全免费',o:'在线'},
  {t:'regex101',u:'https://regex101.com/',d:'最强正则调试器（实时匹配 + 解释）',g:6,s:'在线工具',ty:'正则工具',f:'完全免费',o:'在线'},
  {t:'OneCompiler',u:'https://onecompiler.com/',d:'40+ 语言在线编译运行（C/Java/Python/SQL 等）',g:6,s:'在线工具',ty:'在线编译',f:'完全免费',o:'在线'},
  {t:'tool.lu 程序员工具箱',u:'https://tool.lu/',d:'中文综合开发者工具：代码对比、编码转换、正则、时间戳等',g:6,s:'在线工具',ty:'工具集',f:'完全免费',o:'在线'},
  {t:'VS Code',u:'https://code.visualstudio.com/Download',d:'微软免费开源代码编辑器，装中文语言包即中文化',g:6,s:'免费软件',ty:'软件',f:'完全免费',o:'可下载'},
  {t:'JetBrains 教育授权',u:'https://www.jetbrains.com/community/education/',d:'IDEA / PyCharm 全家桶对学生教师免费一年可续（edu 邮箱或学籍证明）',g:6,s:'免费软件',ty:'软件',f:'学生免费',o:'可下载'},
  {t:'OBS Studio',u:'https://obsproject.com/',d:'开源录屏与直播推流软件，官网有中文界面',g:6,s:'免费软件',ty:'软件',f:'完全免费',o:'可下载'},
  {t:'GIMP',u:'https://www.gimp.org/',d:'开源图像编辑器，Photoshop 免费替代',g:6,s:'免费软件',ty:'软件',f:'完全免费',o:'可下载'},
  {t:'Krita',u:'https://krita.org/zh-cn/',d:'开源数字绘画 / 插画 / 动画软件，有中文官网',g:6,s:'免费软件',ty:'软件',f:'完全免费',o:'可下载'},
  {t:'Blender',u:'https://www.blender.org/',d:'开源全能 3D 建模 / 动画 / 渲染软件',g:6,s:'免费软件',ty:'软件',f:'完全免费',o:'可下载'},
  {t:'LibreOffice',u:'https://zh-cn.libreoffice.org/',d:'开源办公套件简体中文官网，替代 MS Office',g:6,s:'免费软件',ty:'软件',f:'完全免费',o:'可下载'},
  {t:'WPS Office 个人版',u:'https://www.wps.cn/',d:'金山 WPS 个人版免费（含少量广告），中文办公首选',g:6,s:'免费软件',ty:'软件',f:'个人免费',o:'可下载'},
  {t:'7-Zip',u:'https://www.7-zip.org/',d:'开源免费压缩软件，轻量高效',g:6,s:'免费软件',ty:'软件',f:'完全免费',o:'可下载'},
  {t:'Zotero',u:'https://www.zotero.org/',d:'开源文献管理，支持中文界面与海量社区插件',g:6,s:'免费软件',ty:'软件',f:'完全免费',o:'可下载'},
  {t:'Obsidian',u:'https://obsidian.md/',d:'Markdown 双链笔记，个人使用免费，中文界面，完全离线',g:6,s:'免费软件',ty:'软件',f:'个人免费',o:'可下载'},
  {t:'MarkText',u:'https://github.com/marktext/marktext',d:'开源所见即所得 Markdown 编辑器（Typora 免费替代）',g:6,s:'免费软件',ty:'软件·开源',f:'完全免费',o:'可下载'},
  {t:'Flexbox Froggy（中文）',u:'https://flexboxfroggy.com/#zh-cn',d:'用 CSS 游戏拯救青蛙学 Flexbox，24 关，开源可本地部署',g:6,s:'练习闯关',ty:'练习游戏',f:'完全免费',o:'可下载'},
  {t:'Grid Garden（中文）',u:'https://cssgridgarden.com/#zh-cn',d:'同作者 CSS Grid 种胡萝卜游戏，支持中文',g:6,s:'练习闯关',ty:'练习游戏',f:'完全免费',o:'可下载'},
  {t:'JavaScript30',u:'https://javascript30.com/',d:'Wes Bos 30 天原生 JS 挑战，30 个实战小项目，源码开源',g:6,s:'练习闯关',ty:'练习课程',f:'完全免费',o:'可下载'},
  {t:'learn-regex 正则教程',u:'https://github.com/ziishaned/learn-regex',d:'开源正则表达式速成教程，含中文翻译版',g:6,s:'练习闯关',ty:'教程·开源',f:'完全免费',o:'可下载'},
  {t:'SQLite Online',u:'https://sqliteonline.com/',d:'浏览器内免装 SQL 在线练习环境（MySQL/PG/SQLite）',g:6,s:'练习闯关',ty:'练习环境',f:'完全免费',o:'在线'},
  {t:'阿里云开发者社区',u:'https://developer.aliyun.com/',d:'免费云课程、电子书与技术实验（高校学生计划另享免费 ECS）',g:6,s:'云原生运维',ty:'课程·实验',f:'大部分免费',o:'在线'},
  {t:'腾讯云开发者实验室',u:'https://cloud.tencent.com/developer/labs',d:'浏览器内免费云产品动手实验，免本地搭环境',g:6,s:'云原生运维',ty:'实验平台',f:'免费',o:'在线'},
  {t:'KodeKloud 免费课程',u:'https://kodekloud.com/free-courses',d:'DevOps 学习站免费专区：K8s 挑战、Terraform 入门实验等',g:6,s:'云原生运维',ty:'课程·实验',f:'部分免费',o:'在线',w:1}

  /* 算法竞赛之外的补充条目在上方各组内收录 */
  ]
};
